### PR TITLE
Rename 'type' parameter to fix masking built-in function name

### PR DESCRIPTION
**Pull request by iamaziz**
#### Related Issue(s)

- Fix  issue #44

#### Description of Changes

- Rename the parameter `type` in `models.get_embeddings()` to `embedding_type`

### CODE REVIEW

**Comment by iamaziz** [comment]
My bad! I just notice the documentation needs to be updated for this as well http://docs.ampligraph.org/en/latest/examples.html#get-the-embeddings I just updated it now. But not sure how to rebuild the docs.

**Comment by rorymcgrath** [comment]
Hi iamaziz, thank you for the commit. 
The `get_embeddings()` method will be used regularly and calling the parameter `type_` may be a bit confusing. 
Instead `embedding_type` might better explain the parameter.

**Comment by rorymcgrath** [comment]
Sphinx is used to generate the documentation. If you want to update your local documentation you can navigate to the doc directory and type 

> make html

This will regenerate the documentation and place it in the 

> docs/_build/html

directory.
Once the pull request is merged the official documentation will be updated automatically by the Jenkins server.

**Comment by iamaziz** [comment]
Hey, thanks for doc instructions. Yea perhaps `embedding_type` makes more sense :), should I go ahead and update the PR to `embedding_type`?

**Comment by rorymcgrath** [comment]
That would be great :)

**Comment by iamaziz** [comment]
Sure thing, here you go.

**Comment by rorymcgrath** [comment]
Looks good.

**Pull request merged**
